import faker
from faker.providers import BaseProvider
from datetime import datetime
from db_params import column_faker,table_id

faker = faker.Faker("en_IN")


def generate_fake_data(column):
    """
    Function argument = column_name\n
    Returns fake data generated by the
    faker models tuned for the column
    """

    # Get table and column name
    table_name,column_name = str(column).split(".")

    # Generate id for a PK from table_id map
    if column.primary_key:
        return table_id[table_name]+"_"+faker.bothify(text="########")
    
    # Retrieve the faker model for the column
    faker_model = column_faker[f"{str(column)}"]

    # Use the "fake" method to generate fake data
    if faker_model:
        return faker_model.fake(column_name)
    
    # If no faker model, assume nullable column
    return None
