import models
from dbmap import *
tables= [
	models.BankAccount,
	models.CreditReportData,
	models.Merchant,
	models.MerchantBankAccount,
	models.MerchantInitiatedTransaction,
	models.MerchantPartnerService,
	models.NewCol,
	models.Otp,
	models.Partner,
	models.PayinCollection,
	models.PayinCollectionCallbackDump,
	models.PayinCollectionSettlement,
	models.PayinCollectionSettlementCallbackDump,
	models.PayinSettlementBankAccount,
	models.PayinVa,
	models.Qr,
	models.QrOrder,
	models.Service,
	models.State,
	models.TransactionLog,
	models.UPI,
]
table_id={
	"bank_account" : "ba",
	"credit_report_data" : "cs",
	"merchant" : "mc",
	"merchant_bank_account" : "ma",
	"merchant_initiated_transaction" : "mt",
	"merchant_partner_service" : "ms",
	"temp" : "te",
	"manasgay" : "mg",
	"otp" : "ot",
	"partner" : "pa",
	"payin_collection" : "pc",
	"payin_collection_callback_dump" : "pd",
	"payin_collection_settlement" : "ps",
	"payin_collection_settlement_callback_dump" : "py",
	"payin_settlement_bank_account" : "pb",
	"payin_va" : "pv",
	"qr" : "qr",
	"qr_order" : "qo",
	"service" : "sv",
	"state" : "st",
	"transaction_log" : "tl",
	"upi" : "up",
}
column_faker={
	"bank_account.id" : None,
	"bank_account.account_number" : bank_faker,
	"bank_account.account_type" : None,
	"bank_account.ifsc_code" : bank_faker,
	"bank_account.name_on_bank" : name_faker,
	"bank_account.bank_name" : name_faker,
	"bank_account.branch_name" : name_faker,
	"bank_account.verified_by_partner" : None,
	"credit_report_data.id" : None,
	"credit_report_data.merchant" : None,
	"credit_report_data.json_data" : id_faker,
	"merchant.id" : None,
	"merchant.name" : name_faker,
	"merchant.phone" : phone_faker,
	"merchant.bussiness_type" : None,
	"merchant.bussiness_catagory" : None,
	"merchant.email" : None,
	"merchant.checkout_page_link" : url_faker,
	"merchant.status" : None,
	"merchant.onboarding_type" : None,
	"merchant.imei_number" : bank_faker,
	"merchant.digital_qr_code" : None,
	"merchant.annual_turnover" : float_faker,
	"merchant.external_upi" : bank_faker,
	"merchant.dob" : date_faker,
	"merchant.gender" : bank_faker,
	"merchant.rrn" : id_faker,
	"merchant.uri" : id_faker,
	"merchant_bank_account.id" : None,
	"merchant_bank_account.bank_account" : None,
	"merchant_bank_account.merchant" : None,
	"merchant_bank_account.is_primary" : None,
	"merchant_initiated_transaction.id" : None,
	"merchant_initiated_transaction.merchant" : None,
	"merchant_initiated_transaction.remitter_phone_number" : phone_faker,
	"merchant_initiated_transaction.transaction_id" : id_faker,
	"merchant_initiated_transaction.mode" : None,
	"merchant_initiated_transaction.status" : None,
	"merchant_initiated_transaction.link" : url_faker,
	"merchant_initiated_transaction.shortened_link" : url_faker,
	"merchant_initiated_transaction.link_expiry" : date_faker,
	"merchant_partner_service.id" : None,
	"merchant_partner_service.merchant" : None,
	"merchant_partner_service.partner" : None,
	"merchant_partner_service.service" : None,
	"merchant_partner_service.status" : None,
	"temp.id" : None,
	"temp.entity_id" : id_faker,
	"manasgay.id" : None,
	"manasgay.temp" : phone_faker,
	"otp.id" : None,
	"otp.otp" : id_faker,
	"otp.merchant" : None,
	"otp.destination" : None,
	"partner.id" : None,
	"partner.name" : name_faker,
	"payin_collection.id" : None,
	"payin_collection.payin_va" : None,
	"payin_collection.collection_id" : id_faker,
	"payin_collection.amount" : bank_faker,
	"payin_collection.mode" : None,
	"payin_collection.remitter_upi_id" : bank_faker,
	"payin_collection.remitter_account_number" : bank_faker,
	"payin_collection.remitter_ifsc_code" : bank_faker,
	"payin_collection.remitter_name" : name_faker,
	"payin_collection.remitter_phone_number" : phone_faker,
	"payin_collection.utr" : bank_faker,
	"payin_collection.remarks" : None,
	"payin_collection.merchant_initiated_transaction" : None,
	"payin_collection.request_hostname" : name_faker,
	"payin_collection.payin_collection_settlement" : None,
	"payin_collection_callback_dump.id" : None,
	"payin_collection_callback_dump.payin_collection" : None,
	"payin_collection_callback_dump.dump" : None,
	"payin_collection_settlement.id" : None,
	"payin_collection_settlement.batch_id" : id_faker,
	"payin_collection_settlement.amount" : float_faker,
	"payin_collection_settlement.status" : None,
	"payin_collection_settlement.initiated_by" : None,
	"payin_collection_settlement.collection_ids" : None,
	"payin_collection_settlement.payin_settlement_bank_account" : None,
	"payin_collection_settlement_callback_dump.id" : None,
	"payin_collection_settlement_callback_dump.payin_collection_settlement" : None,
	"payin_collection_settlement_callback_dump.settlement_json_dump" : None,
	"payin_settlement_bank_account.id" : None,
	"payin_settlement_bank_account.payin_va" : None,
	"payin_settlement_bank_account.merchant_bank_account" : None,
	"payin_settlement_bank_account.kyc_status" : None,
	"payin_va.id" : None,
	"payin_va.va" : bank_faker,
	"payin_va.ifsc" : bank_faker,
	"payin_va.vpa" : bank_faker,
	"payin_va.merchant_partner_service" : None,
	"payin_va.status" : None,
	"payin_va.reject_reason" : None,
	"qr.id" : None,
	"qr.value" : id_faker,
	"qr_order.id" : None,
	"qr_order.qr_code" : None,
	"qr_order.merchant" : None,
	"qr_order.order_date" : date_faker,
	"qr_order.payment_mode" : None,
	"qr_order.order_status" : None,
	"qr_order.delivery_date" : date_faker,
	"qr_order.request_id" : id_faker,
	"qr_order.article_id" : id_faker,
	"qr_order.amount" : float_faker,
	"qr_order.payment_url" : url_faker,
	"qr_order.refernce_id" : url_faker,
	"qr_order.pickup_date" : date_faker,
	"qr_order.remark" : None,
	"qr_order.pincode_available_for_delivery" : None,
	"qr_order.base_tariff" : float_faker,
	"qr_order.pickup_charges" : float_faker,
	"qr_order.total_tariff" : float_faker,
	"qr_order.label_url" : url_faker,
	"qr_order.reorder_for_qr" : None,
	"service.id" : None,
	"service.name" : name_faker,
	"service.is_primary_payin_account" : None,
	"service.is_primary_payout_account" : None,
	"state.id" : None,
	"state.value" : id_faker,
	"transaction_log.id" : None,
	"transaction_log.entity_type" : None,
	"transaction_log.entity_id" : id_faker,
	"transaction_log.action" : None,
	"transaction_log.timestamp" : date_faker,
	"upi.id" : None,
	"upi.upi_id" : bank_faker,
	"upi.name_on_bank" : name_faker,
	"upi.verified_by_partner" : None,
	"upi.verification_initiated_by_partner" : None,
}
