"""empty message

Revision ID: 43da1cc2ce81
Revises: b284c863a987
Create Date: 2023-07-14 16:10:46.854209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43da1cc2ce81'
down_revision = 'b284c863a987'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('votes_user_id_fkey', 'votes', type_='foreignkey')
    op.drop_column('votes', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('votes', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('votes_user_id_fkey', 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
