version : "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    # env_file:
    #   - ./.env 
    environment:
      - DATABASE_HOSTNAME=postgres
      - DATABASE_PORT=5432
      - DATABASE_PASSWORD=g
      - DATABASE_NAME=test
      - SECRET_KEY=a2fdfwf4132532dsf422
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRATION_TIME_MINUTES=30
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=g
      - POSTGRES_DB=test
    volumes:
      - postgres-db:/var/lib/postgres/data
volumes:
  postgres-db: